apiVersion: v1
kind: Pod
metadata:
  name: hpa-demo
spec:
  containers:
  - name: hpa-demo-container
    image: nginx:latest
    resources:
      limits:
        cpu: 200m
      requests:
        cpu: 100m
