apiVersion: v1
kind: Namespace
metadata:
  name: product1
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: product1
spec:
  hard:
    pods: "10"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
